"""Single source of truth for NCAAB team-name normalisation.

Keys are the names other data sources use (The Odds API / ESPN style "Duke Blue Devils"),
values are the canonical NCAA.com institution names that the NCAA scoreboard API returns.
Every module (train, predict, grade, logo builder) must import from here.
"""
from __future__ import annotations

import re
import unicodedata

TEAM_NAME_MAP: dict[str, str] = {
    'Abilene Christian Wildcats': 'Abilene Christian University',
    'Air Force Falcons': 'United States Air Force Academy',
    'Akron Zips': 'University of Akron',
    'Alabama A&M Bulldogs': 'Alabama A&M University',
    'Alabama Crimson Tide': 'University of Alabama',
    'Alabama St Hornets': 'Alabama State University',
    'Alabama State Hornets': 'Alabama State University',
    'Albany Great Danes': 'University at Albany',
    'Alcorn St Braves': 'Alcorn State University',
    'Alcorn State Braves': 'Alcorn State University',
    'American Eagles': 'American University',
    'App St Mountaineers': 'Appalachian State University',
    'App State Mountaineers': 'Appalachian State University',
    'Appalachian St Mountaineers': 'Appalachian State University',
    'Appalachian State Mountaineers': 'Appalachian State University',
    'Arizona St Sun Devils': 'Arizona State University',
    'Arizona State Sun Devils': 'Arizona State University',
    'Arizona Wildcats': 'University of Arizona',
    'Arkansas Pine Bluff Golden Lions': 'University of Arkansas at Pine Bluff',
    'Arkansas Razorbacks': 'University of Arkansas',
    'Arkansas St Red Wolves': 'Arkansas State University',
    'Arkansas State Red Wolves': 'Arkansas State University',
    'Arkansas-Pine Bluff Golden Lions': 'University of Arkansas at Pine Bluff',
    'Army Knights': 'U.S. Military Academy',
    'Auburn Tigers': 'Auburn University',
    'Austin Peay Governors': 'Austin Peay State University',
    'Ball St Cardinals': 'Ball State University',
    'Ball State Cardinals': 'Ball State University',
    'Baylor Bears': 'Baylor University',
    'Bellarmine Knights': 'Bellarmine University',
    'Belmont Bruins': 'Belmont University',
    'Bethune Cookman Wildcats': 'Bethune-Cookman University',
    'Bethune-Cookman Wildcats': 'Bethune-Cookman University',
    'Binghamton Bearcats': 'Binghamton University',
    'Boise St Broncos': 'Boise State University',
    'Boise State Broncos': 'Boise State University',
    'Boston College Eagles': 'Boston College',
    'Boston Univ. Terriers': 'Boston University',
    'Bowling Green Falcons': 'Bowling Green State University',
    'Bradley Braves': 'Bradley University',
    'Brown Bears': 'Brown University',
    'Bryant Bulldogs': 'Bryant University',
    'Bucknell Bison': 'Bucknell University',
    'Buffalo Bulls': 'University at Buffalo',
    'Butler Bulldogs': 'Butler University',
    'BYU Cougars': 'Brigham Young University',
    'Cal Baptist Lancers': 'California Baptist University',
    'Cal Golden Bears': 'University of California, Berkeley',
    'Cal Poly Mustangs': 'California Polytechnic State University',
    'Cal St Bakersfield Roadrunners': 'California State University, Bakersfield',
    'Cal St Fullerton Titans': 'California State University, Fullerton',
    'Cal St Northridge Matadors': 'California State University, Northridge',
    'Cal State Bakersfield Roadrunners': 'California State University, Bakersfield',
    'Cal State Fullerton Titans': 'California State University, Fullerton',
    'Cal State Northridge Matadors': 'California State University, Northridge',
    'California Golden Bears': 'University of California, Berkeley',
    'Campbell Fighting Camels': 'Campbell University',
    'Canisius Golden Griffins': 'Canisius University',
    'Central Arkansas Bears': 'University of Central Arkansas',
    'Central Connecticut Blue Devils': 'Central Connecticut State University',
    'Central Florida': 'University of Central Florida',
    'Central Michigan Chippewas': 'Central Michigan University',
    'Charleston (SC) Cougars': 'College of Charleston (South Carolina)',
    'Charleston Cougars': 'College of Charleston (South Carolina)',
    'Charleston Southern Buccaneers': 'Charleston Southern University',
    'Charlotte 49ers': 'The University of North Carolina at Charlotte',
    'Chattanooga Mocs': 'The University of Tennessee at Chattanooga',
    'Chicago St Cougars': 'Chicago State University',
    'Chicago State Cougars': 'Chicago State University',
    'Cincinnati Bearcats': 'University of Cincinnati',
    'Clemson Tigers': 'Clemson University',
    'Cleveland St Vikings': 'Cleveland State University',
    'Cleveland State Vikings': 'Cleveland State University',
    'Coastal Carolina Chanticleers': 'Coastal Carolina University',
    'Colgate Raiders': 'Colgate University',
    'Colorado Buffaloes': 'University of Colorado, Boulder',
    'Colorado St Rams': 'Colorado State University',
    'Colorado State Rams': 'Colorado State University',
    'Columbia Lions': 'Columbia University',
    'Connecticut Huskies': 'University of Connecticut',
    'Coppin St Eagles': 'Coppin State University',
    'Coppin State Eagles': 'Coppin State University',
    'Cornell Big Red': 'Cornell University',
    'Creighton Bluejays': 'Creighton University',
    'CSU Rams': 'Colorado State University',
    'Dartmouth Big Green': 'Dartmouth College',
    'Davidson Wildcats': 'Davidson College',
    'Dayton Flyers': 'University of Dayton',
    'Delaware Blue Hens': 'University of Delaware',
    'Delaware St Hornets': 'Delaware State University',
    'Delaware State Hornets': 'Delaware State University',
    'Denver Pioneers': 'University of Denver',
    'DePaul Blue Demons': 'DePaul University',
    'Detroit Mercy Titans': 'University of Detroit Mercy',
    'Detroit Titans': 'University of Detroit Mercy',
    'Dixie St Trailblazers': 'Utah Tech University',
    'Dixie State Trailblazers': 'Utah Tech University',
    'Drake Bulldogs': 'Drake University',
    'Drexel Dragons': 'Drexel University',
    'Duke Blue Devils': 'Duke University',
    'Duquesne Dukes': 'Duquesne University',
    'East Carolina Pirates': 'East Carolina University',
    'East Tennessee St Buccaneers': 'East Tennessee State University',
    'East Tennessee State Buccaneers': 'East Tennessee State University',
    'Eastern Illinois Panthers': 'Eastern Illinois University',
    'Eastern Kentucky Colonels': 'Eastern Kentucky University',
    'Eastern Michigan Eagles': 'Eastern Michigan University',
    'Eastern Washington Eagles': 'Eastern Washington University',
    'Elon Phoenix': 'Elon University',
    'Evansville Purple Aces': 'University of Evansville',
    'Fairfield Stags': 'Fairfield University',
    'Fairleigh Dickinson Knights': 'Fairleigh Dickinson University',
    'FGCU Eagles': 'Florida Gulf Coast University',
    'FIU Panthers': 'Florida International University',
    'Florida A&M Rattlers': 'Florida A&M University',
    'Florida Atlantic Owls': 'Florida Atlantic University',
    'Florida Gators': 'University of Florida',
    "Florida Int'l Golden Panthers": 'Florida International University',
    'Florida Intl Golden Panthers': 'Florida International University',
    'Florida St Seminoles': 'Florida State University',
    'Florida State Seminoles': 'Florida State University',
    'Fordham Rams': 'Fordham University',
    'Fort Wayne Mastodons': 'Purdue University Fort Wayne',
    'Fresno St Bulldogs': 'California State University, Fresno',
    'Fresno State Bulldogs': 'California State University, Fresno',
    'Furman Paladins': 'Furman University',
    'Gardner-Webb Bulldogs': 'Gardner-Webb University',
    'George Mason Patriots': 'George Mason University',
    'George Washington Colonials': 'George Washington University',
    'George Washington Revolutionaries': 'George Washington University',
    'Georgetown Hoyas': 'Georgetown University',
    'Georgia Bulldogs': 'University of Georgia',
    'Georgia Southern Eagles': 'Georgia Southern University',
    'Georgia St Panthers': 'Georgia State University',
    'Georgia State Panthers': 'Georgia State University',
    'Georgia Tech Yellow Jackets': 'Georgia Institute of Technology',
    'Gonzaga Bulldogs': 'Gonzaga University',
    'Grambling St Tigers': 'Grambling State University',
    'Grambling State Tigers': 'Grambling State University',
    'Grambling Tigers': 'Grambling State University',
    'Grand Canyon Antelopes': 'Grand Canyon University',
    'Green Bay Phoenix': 'University of Wisconsin-Green Bay',
    'Hampton Pirates': 'Hampton University',
    'Hartford Hawks': 'University of Hartford',
    'Harvard Crimson': 'Harvard University',
    "Hawai'i Rainbow Warriors": 'University of Hawaii, Manoa',
    'Hawaii Rainbow Warriors': 'University of Hawaii, Manoa',
    'High Point Panthers': 'High Point University',
    'Hofstra Pride': 'Hofstra University',
    'Holy Cross Crusaders': 'College of the Holy Cross',
    'Houston Christian Huskies': 'Houston Christian University',
    'Houston Cougars': 'University of Houston',
    'Howard Bison': 'Howard University',
    'Idaho St Bengals': 'Idaho State University',
    'Idaho State Bengals': 'Idaho State University',
    'Idaho Vandals': 'University of Idaho',
    'Illinois': 'University of Illinois',
    'Illinois Chicago Flames': 'University of Illinois Chicago',
    'Illinois Fighting Illini': 'University of Illinois',
    'Illinois St Redbirds': 'Illinois State University',
    'Illinois State Redbirds': 'Illinois State University',
    'Incarnate Word Cardinals': 'University of the Incarnate Word',
    'Indiana Hoosiers': 'Indiana University, Bloomington',
    'Indiana St Sycamores': 'Indiana State University',
    'Indiana State Sycamores': 'Indiana State University',
    'Iona Gaels': 'Iona University',
    'Iowa Hawkeyes': 'University of Iowa',
    'Iowa St Cyclones': 'Iowa State University',
    'Iowa State': 'Iowa State University',
    'Iowa State Cyclones': 'Iowa State University',
    'IU Indianapolis Jaguars': 'Indiana University Indianapolis',
    'IU Indy Jaguars': 'Indiana University Indianapolis',
    'IUPUI Jaguars': 'Indiana University Indianapolis',
    'Jackson St Tigers': 'Jackson State University',
    'Jackson State Tigers': 'Jackson State University',
    'Jacksonville Dolphins': 'Jacksonville University',
    'Jacksonville St Gamecocks': 'Jacksonville State University',
    'Jacksonville State Gamecocks': 'Jacksonville State University',
    'James Madison Dukes': 'James Madison University',
    'Kansas City Roos': 'University of Missouri-Kansas City',
    'Kansas Jayhawks': 'University of Kansas',
    'Kansas St Wildcats': 'Kansas State University',
    'Kansas State Wildcats': 'Kansas State University',
    'Kennesaw St Owls': 'Kennesaw State University',
    'Kennesaw State Owls': 'Kennesaw State University',
    'Kent St Golden Flashes': 'Kent State University',
    'Kent State Golden Flashes': 'Kent State University',
    'Kentucky Wildcats': 'University of Kentucky',
    'La Salle Explorers': 'La Salle University',
    'Lafayette Leopards': 'Lafayette College',
    'Lamar Cardinals': 'Lamar University',
    'Le Moyne Dolphins': 'Le Moyne College',
    'Lehigh Mountain Hawks': 'Lehigh University',
    'Liberty Flames': 'Liberty University',
    'Lindenwood Lions': 'Lindenwood University',
    'Lipscomb Bisons': 'Lipscomb University',
    'Little Rock Trojans': 'University of Arkansas at Little Rock',
    'LIU Sharks': 'Long Island University',
    'Long Beach St 49ers': 'California State University, Long Beach',
    'Long Beach St Beach': 'California State University, Long Beach',
    'Long Beach State 49ers': 'California State University, Long Beach',
    'Long Beach State Beach': 'California State University, Long Beach',
    'Longwood Lancers': 'Longwood University',
    "Louisiana Ragin' Cajuns": 'University of Louisiana at Lafayette',
    'Louisiana Tech Bulldogs': 'Louisiana Tech University',
    'Louisville Cardinals': 'University of Louisville',
    'Loyola (Chi) Ramblers': 'Loyola University Chicago',
    'Loyola (MD) Greyhounds': 'Loyola University Maryland',
    'Loyola Chicago Ramblers': 'Loyola University Chicago',
    'Loyola Marymount Lions': 'Loyola Marymount University',
    'LSU Tigers': 'Louisiana State University',
    'Maine Black Bears': 'University of Maine',
    'Manhattan Jaspers': 'Manhattan College',
    'Marist Red Foxes': 'Marist College',
    'Marquette Golden Eagles': 'Marquette University',
    'Marshall Thundering Herd': 'Marshall University',
    'Maryland Eastern Shore Hawks': 'University of Maryland Eastern Shore',
    'Maryland Terrapins': 'University of Maryland',
    'Massachusetts Minutemen': 'University of Massachusetts Amherst',
    'McNeese Cowboys': 'McNeese State University',
    'Memphis Tigers': 'University of Memphis',
    'Mercer Bears': 'Mercer University',
    'Mercyhurst Lakers': 'Mercyhurst University',
    'Merrimack Warriors': 'Merrimack College',
    'Miami (FL) Hurricanes': 'University of Miami (Florida)',
    'Miami (OH) RedHawks': 'Miami University',
    'Miami Hurricanes': 'University of Miami (Florida)',
    'Miami RedHawks': 'Miami University',
    'Michigan St Spartans': 'Michigan State University',
    'Michigan State Spartans': 'Michigan State University',
    'Michigan Wolverines': 'University of Michigan',
    'Middle Tennessee Blue Raiders': 'Middle Tennessee State University',
    'Milwaukee Panthers': 'University of Wisconsin-Milwaukee',
    'Minnesota Golden Gophers': 'University of Minnesota, Twin Cities',
    'Mississippi St Bulldogs': 'Mississippi State University',
    'Mississippi State Bulldogs': 'Mississippi State University',
    'Mississippi Valley St Delta Devils': 'Mississippi Valley State University',
    'Mississippi Valley State Delta Devils': 'Mississippi Valley State University',
    'Missouri St Bears': 'Missouri State University',
    'Missouri State Bears': 'Missouri State University',
    'Missouri Tigers': 'University of Missouri, Columbia',
    'Monmouth Hawks': 'Monmouth University',
    'Montana Grizzlies': 'University of Montana',
    'Montana St Bobcats': 'Montana State University',
    'Montana State Bobcats': 'Montana State University',
    'Morehead St Eagles': 'Morehead State University',
    'Morehead State Eagles': 'Morehead State University',
    'Morgan St Bears': 'Morgan State University',
    'Morgan State Bears': 'Morgan State University',
    "Mount St Mary's Mountaineers": "Mount St. Mary's University",
    "Mount St. Mary's Mountaineers": "Mount St. Mary's University",
    "Mount State Mary's Mountaineers": "Mount St. Mary's University",
    'Murray St Racers': 'Murray State University',
    'Murray State Racers': 'Murray State University',
    'Navy Midshipmen': 'United States Naval Academy',
    'NC St Wolfpack': 'North Carolina State University',
    'NC State Wolfpack': 'North Carolina State University',
    'Nebraska Cornhuskers': 'University of Nebraska-Lincoln',
    'Nebraska Omaha Mavericks': 'University of Nebraska Omaha',
    'Nevada Wolf Pack': 'University of Nevada, Reno',
    'New Hampshire Wildcats': 'University of New Hampshire',
    'New Mexico Lobos': 'University of New Mexico',
    'New Mexico St Aggies': 'New Mexico State University',
    'New Mexico State Aggies': 'New Mexico State University',
    'New Orleans Privateers': 'University of New Orleans',
    'Niagara Purple Eagles': 'Niagara University',
    'Nicholls Colonels': 'Nicholls State University',
    'NJIT Highlanders': 'New Jersey Institute of Technology',
    'Norfolk St Spartans': 'Norfolk State University',
    'Norfolk State Spartans': 'Norfolk State University',
    'North Carolina A&T Aggies': 'North Carolina A&T State University',
    'North Carolina Central Eagles': 'North Carolina Central University',
    'North Carolina Tar Heels': 'University of North Carolina at Chapel Hill',
    'North Carolina Tarheels': 'University of North Carolina at Chapel Hill',
    'North Dakota Fighting Hawks': 'University of North Dakota',
    'North Dakota St Bison': 'North Dakota State University',
    'North Dakota State Bison': 'North Dakota State University',
    'North Florida Ospreys': 'University of North Florida',
    'North Texas Mean Green': 'University of North Texas',
    'Northeastern Huskies': 'Northeastern University',
    'Northern Arizona Lumberjacks': 'Northern Arizona University',
    'Northern Colorado Bears': 'University of Northern Colorado',
    'Northern Illinois Huskies': 'Northern Illinois University',
    'Northern Iowa Panthers': 'University of Northern Iowa',
    'Northern Kentucky Norse': 'Northern Kentucky University',
    'Northwestern St Demons': 'Northwestern State University',
    'Northwestern State Demons': 'Northwestern State University',
    'Northwestern Wildcats': 'Northwestern University',
    'Notre Dame Fighting Irish': 'University of Notre Dame',
    'Oakland Golden Grizzlies': 'Oakland University',
    'Ohio Bobcats': 'Ohio University',
    'Ohio St Buckeyes': 'The Ohio State University',
    'Ohio State Buckeyes': 'The Ohio State University',
    'Oklahoma Sooners': 'University of Oklahoma',
    'Oklahoma St Cowboys': 'Oklahoma State University',
    'Oklahoma State Cowboys': 'Oklahoma State University',
    'Old Dominion Monarchs': 'Old Dominion University',
    'Ole Miss Rebels': 'University of Mississippi',
    'Omaha Mavericks': 'University of Nebraska Omaha',
    'Oral Roberts Golden Eagles': 'Oral Roberts University',
    'Oregon Ducks': 'University of Oregon',
    'Oregon St Beavers': 'Oregon State University',
    'Oregon State Beavers': 'Oregon State University',
    'Pacific Tigers': 'University of the Pacific',
    'Penn St Nittany Lions': 'Pennsylvania State University',
    'Penn State Nittany Lions': 'Pennsylvania State University',
    'Pennsylvania Quakers': 'University of Pennsylvania',
    'Pepperdine Waves': 'Pepperdine University',
    'Pitt Panthers': 'University of Pittsburgh',
    'Pittsburgh Panthers': 'University of Pittsburgh',
    'Portland Pilots': 'University of Portland',
    'Portland St Vikings': 'Portland State University',
    'Portland State Vikings': 'Portland State University',
    'Prairie View A&M Panthers': 'Prairie View A&M University',
    'Prairie View Panthers': 'Prairie View A&M University',
    'Presbyterian Blue Hose': 'Presbyterian College',
    'Princeton Tigers': 'Princeton University',
    'Providence Friars': 'Providence College',
    'Purdue Boilermakers': 'Purdue University',
    'Purdue Fort Wayne Mastodons': 'Purdue University Fort Wayne',
    'Queens University Royals': 'Queens University of Charlotte',
    'Quinnipiac Bobcats': 'Quinnipiac University',
    'Radford Highlanders': 'Radford University',
    'Rhode Island Rams': 'University of Rhode Island',
    'Rice Owls': 'Rice University',
    'Richmond Spiders': 'University of Richmond',
    'Rider Broncs': 'Rider University',
    'Robert Morris Colonials': 'Robert Morris University',
    'Rutgers Scarlet Knights': 'Rutgers, The State University of New Jersey, New Brunswick',
    'Sacramento St Hornets': 'California State University, Sacramento',
    'Sacramento State Hornets': 'California State University, Sacramento',
    'Sacred Heart Pioneers': 'Sacred Heart University',
    'Saint Francis Red Flash': 'Saint Francis University (Pennsylvania)',
    "Saint Joseph's Hawks": "Saint Joseph's University",
    'Saint Louis Billikens': 'Saint Louis University',
    "Saint Mary's Gaels": "Saint Mary's College of California",
    "Saint Peter's Peacocks": "Saint Peter's University",
    'Sam Houston Bearkats': 'Sam Houston State University',
    'Sam Houston St Bearkats': 'Sam Houston State University',
    'Sam Houston State Bearkats': 'Sam Houston State University',
    'Samford Bulldogs': 'Samford University',
    'San Diego St Aztecs': 'San Diego State University',
    'San Diego State Aztecs': 'San Diego State University',
    'San Diego Toreros': 'University of San Diego',
    'San Francisco Dons': 'University of San Francisco',
    'San José St Spartans': 'San Jose State University',
    'San José State Spartans': 'San Jose State University',
    'Santa Clara Broncos': 'Santa Clara University',
    'Savannah St Tigers': 'Savannah State University',
    'Savannah State Tigers': 'Savannah State University',
    'SE Louisiana Lions': 'Southeastern Louisiana University',
    'SE Missouri St Redhawks': 'Southeast Missouri State University',
    'SE Missouri State Redhawks': 'Southeast Missouri State University',
    'Seattle Redhawks': 'Seattle University',
    'Seattle U Redhawks': 'Seattle University',
    'Seton Hall Pirates': 'Seton Hall University',
    'Siena Saints': 'Siena College',
    'SIU Edwardsville Cougars': 'Southern Illinois University Edwardsville',
    'SMU Mustangs': 'Southern Methodist University',
    'South Alabama Jaguars': 'University of South Alabama',
    'South Carolina Gamecocks': 'University of South Carolina, Columbia',
    'South Carolina St Bulldogs': 'South Carolina State University',
    'South Carolina State Bulldogs': 'South Carolina State University',
    'South Dakota Coyotes': 'University of South Dakota',
    'South Dakota St Jackrabbits': 'South Dakota State University',
    'South Dakota State Jackrabbits': 'South Dakota State University',
    'South Florida Bulls': 'University of South Florida',
    'Southeast Missouri St Redhawks': 'Southeast Missouri State University',
    'Southeast Missouri State Redhawks': 'Southeast Missouri State University',
    'Southeastern Louisiana Lions': 'Southeastern Louisiana University',
    'Southern Illinois Salukis': 'Southern Illinois University at Carbondale',
    'Southern Indiana Screaming Eagles': 'University of Southern Indiana',
    'Southern Jaguars': 'Southern University and A&M College',
    'Southern Miss Golden Eagles': 'The University of Southern Mississippi',
    'Southern Utah Thunderbirds': 'Southern Utah University',
    'St. Bonaventure Bonnies': 'St. Bonaventure University',
    'St. Francis (BKN) Terriers': 'St. Francis College Brooklyn',
    'St. Francis (PA) Red Flash': 'Saint Francis University (Pennsylvania)',
    'St. Francis Brooklyn Terriers': 'St. Francis College Brooklyn',
    "St. John's Red Storm": "St. John's University",
    "St. Peter's Peacocks": "Saint Peter's University",
    'St. Thomas (MN) Tommies': 'University of St. Thomas',
    'St. Thomas Tommies': 'University of St. Thomas',
    'Stanford Cardinal': 'Stanford University',
    'Stephen F Austin Lumberjacks': 'Stephen F. Austin State University',
    'Stephen F. Austin Lumberjacks': 'Stephen F. Austin State University',
    'Stetson Hatters': 'Stetson University',
    'Stony Brook Seawolves': 'Stony Brook University',
    'Syracuse Orange': 'Syracuse University',
    'Tarleton St Texans': 'Tarleton State University',
    'Tarleton State Texans': 'Tarleton State University',
    'TCU Horned Frogs': 'Texas Christian University',
    'Temple Owls': 'Temple University',
    'Tennessee St Tigers': 'Tennessee State University',
    'Tennessee State Tigers': 'Tennessee State University',
    'Tennessee Tech Golden Eagles': 'Tennessee Technological University',
    'Tennessee Volunteers': 'University of Tennessee, Knoxville',
    'Texas A&M Aggies': 'Texas A&M University, College Station',
    'Texas A&M-CC Islanders': 'Texas A&M University-Corpus Christi',
    'Texas A&M-Corpus Christi Islanders': 'Texas A&M University-Corpus Christi',
    'Texas Longhorns': 'University of Texas at Austin',
    'Texas Southern Tigers': 'Texas Southern University',
    'Texas St Bobcats': 'Texas State University',
    'Texas State Bobcats': 'Texas State University',
    'Texas Tech Red Raiders': 'Texas Tech University',
    'Texas-Arlington Mavericks': 'University of Texas at Arlington',
    'The Citadel Bulldogs': 'The Citadel',
    'Toledo Rockets': 'University of Toledo',
    'Towson Tigers': 'Towson University',
    'Troy Trojans': 'Troy University',
    'Tulane Green Wave': 'Tulane University',
    'Tulsa Golden Hurricane': 'University of Tulsa',
    'UAB Blazers': 'University of Alabama at Birmingham',
    'UC Davis Aggies': 'University of California, Davis',
    'UC Irvine Anteaters': 'University of California, Irvine',
    'UC Riverside Highlanders': 'University of California, Riverside',
    'UC San Diego Tritons': 'University of California, San Diego',
    'UC Santa Barbara Gauchos': 'University of California, Santa Barbara',
    'UCF Knights': 'University of Central Florida',
    'UCLA Bruins': 'University of California, Los Angeles',
    'UConn Huskies': 'University of Connecticut',
    'UIC Flames': 'University of Illinois Chicago',
    'UIW Cardinals': 'University of the Incarnate Word',
    'UL Monroe Warhawks': 'University of Louisiana Monroe',
    'UMass Amherst Minutemen': 'University of Massachusetts Amherst',
    'UMass Lowell River Hawks': 'University of Massachusetts Lowell',
    'UMass Minutemen': 'University of Massachusetts Amherst',
    'UMKC Kangaroos': 'University of Missouri-Kansas City',
    'UMKC Roos': 'University of Missouri-Kansas City',
    'UNC Asheville Bulldogs': 'University of North Carolina Asheville',
    'UNC Greensboro Spartans': 'The University of North Carolina at Greensboro',
    'UNC Tar Heels': 'University of North Carolina at Chapel Hill',
    'UNC Wilmington Seahawks': 'University of North Carolina Wilmington',
    'UNCW Seahawks': 'University of North Carolina Wilmington',
    'University of Illinois Urbana-Champaign': 'University of Illinois',
    'UNLV Rebels': 'University of Nevada, Las Vegas',
    'USC Trojans': 'University of Southern California',
    'USC Upstate Spartans': 'University of South Carolina Upstate',
    'UT Martin Skyhawks': 'University of Tennessee at Martin',
    'UT Rio Grande Valley Vaqueros': 'University of Texas Rio Grande Valley',
    'UT-Arlington Mavericks': 'University of Texas at Arlington',
    'Utah St Aggies': 'Utah State University',
    'Utah State Aggies': 'Utah State University',
    'Utah Tech Trailblazers': 'Utah Tech University',
    'Utah Utes': 'University of Utah',
    'Utah Valley Wolverines': 'Utah Valley University',
    'UTEP Miners': 'University of Texas at El Paso',
    'UTRGV Vaqueros': 'University of Texas Rio Grande Valley',
    'UTSA Roadrunners': 'University of Texas at San Antonio',
    'Valparaiso Beacons': 'Valparaiso University',
    'Vanderbilt Commodores': 'Vanderbilt University',
    'VCU Rams': 'Virginia Commonwealth University',
    'Vermont Catamounts': 'University of Vermont',
    'Villanova Wildcats': 'Villanova University',
    'Virginia Cavaliers': 'University of Virginia',
    'Virginia Tech Hokies': 'Virginia Polytechnic Institute and State University',
    'VMI Keydets': 'Virginia Military Institute',
    'Wagner Seahawks': 'Wagner College',
    'Wake Forest Demon Deacons': 'Wake Forest University',
    'Washington Huskies': 'University of Washington',
    'Washington St Cougars': 'Washington State University',
    'Washington State Cougars': 'Washington State University',
    'Weber St Wildcats': 'Weber State University',
    'Weber State Wildcats': 'Weber State University',
    'West Georgia Wolves': 'University of West Georgia',
    'West Virginia Mountaineers': 'West Virginia University',
    'Western Carolina Catamounts': 'Western Carolina University',
    'Western Illinois Leathernecks': 'Western Illinois University',
    'Western Kentucky Hilltoppers': 'Western Kentucky University',
    'Western Michigan Broncos': 'Western Michigan University',
    'Wichita St Shockers': 'Wichita State University',
    'Wichita State Shockers': 'Wichita State University',
    'Winthrop Eagles': 'Winthrop University',
    'Wisconsin Badgers': 'University of Wisconsin-Madison',
    'Wofford Terriers': 'Wofford College',
    'Wyoming Cowboys': 'University of Wyoming',
    'Xavier Musketeers': 'Xavier University',
    'Yale Bulldogs': 'Yale University',
    'Youngstown St Penguins': 'Youngstown State University',
    'Youngstown State Penguins': 'Youngstown State University',
}

# Canonical names (the value side) map to themselves so already-canonical input is a no-op.
_CANON = {v: v for v in TEAM_NAME_MAP.values()}


def _clean(name: str) -> str:
    """Lower-case, strip accents/punctuation, collapse whitespace - used only as a lookup key."""
    name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    name = name.replace("&", "and").replace("'", "").replace("’", "")
    name = re.sub(r"[^a-z0-9 ]+", " ", name.lower())
    return re.sub(r"\s+", " ", name).strip()


_LOOKUP = {_clean(k): v for k, v in TEAM_NAME_MAP.items()}
_LOOKUP.update({_clean(v): v for v in _CANON})

UNMAPPED: set[str] = set()


def normalize_team_name(name):
    """Return the canonical NCAA institution name for *name*.

    Falls back to a punctuation/case-insensitive lookup, then returns the input unchanged
    while recording it in UNMAPPED so the caller can report it.
    """
    if name is None or (isinstance(name, float)):
        return name
    s = str(name).strip()
    if s in TEAM_NAME_MAP:
        return TEAM_NAME_MAP[s]
    if s in _CANON:
        return s
    hit = _LOOKUP.get(_clean(s))
    if hit:
        return hit
    UNMAPPED.add(s)
    return s


def report_unmapped(logger=None) -> list[str]:
    """Log and return every name that fell through normalisation this run."""
    names = sorted(UNMAPPED)
    if names and logger:
        logger.warning("%d team names could not be normalised - add them to TEAM_NAME_MAP: %s",
                       len(names), names)
    return names
